Upstream update for upcoming public version.

diff --git a/wooper/GNUmakefile b/wooper/GNUmakefile
--- a/wooper/GNUmakefile
+++ b/wooper/GNUmakefile
@@ -1,12 +1,12 @@
 WOOPER_TOP = .
 
 
-.PHONY: help help-intro help-wooper                                    \
-		all register-version-in-header register-wooper list-beam-dirs  \
-		add-prerequisite-plts link-plt                                 \
-		release release-zip release-bz2 release-xz                     \
-		prepare-release clean-release clean-archive stats              \
-		info-context info-versions info-paths                          \
+.PHONY: help help-intro help-wooper                                        \
+		all register-version-in-header register-wooper list-beam-dirs      \
+		add-prerequisite-plts link-plt                                     \
+		release release-zip release-bz2 release-xz                         \
+		prepare-release clean-release clean-archive stats                  \
+		info-context info-versions info-paths                              \
 		info-compile info-conditionals info-deps
 
 
@@ -36,9 +36,9 @@ help-wooper:
 
 
 register-version-in-header:
-	@if [ -z "$(VERSION_FILE)" ] ; then \
-	echo "Error, no version file defined." 1>&2 ; exit 51 ; else \
-	$(MAKE) register-wooper ; fi
+	@if [ -z "$(VERSION_FILE)" ]; then \
+	echo "Error, no version file defined." 1>&2; exit 51; else \
+	$(MAKE) register-wooper; fi
 
 
 register-wooper:
@@ -47,7 +47,7 @@ register-wooper:
 
 # Useful to extract internal layout for re-use in upper layers:
 list-beam-dirs:
-	@for d in $(WOOPER_BEAM_DIRS) ; do echo $$(readlink -f $$d) ; done
+	@for d in $(WOOPER_BEAM_DIRS); do echo $$(readlink -f $$d); done
 
 
 add-prerequisite-plts: link-plt
@@ -55,7 +55,7 @@ add-prerequisite-plts: link-plt
 
 # As upper layers may rely on the 'wooper' naming:
 link-plt:
-	@if [ ! "$(PLT_FILE)" = "$(WOOPER_PLT_FILE)" ]; then /bin/ln -s --force $(PLT_FILE) $(WOOPER_PLT_FILE) ; fi
+	@if [ ! "$(PLT_FILE)" = "$(WOOPER_PLT_FILE)" ]; then /bin/ln -s --force $(PLT_FILE) $(WOOPER_PLT_FILE); fi
 
 
 # Note: the source archives are not produced in this directory, but in its
